name: "Check if symbols need to be regenerated"
on:
  workflow_dispatch:
  push:
    paths:
    - 'openrtx/include/fonts/symbols/**/*'
  pull_request:
    paths:
      - 'openrtx/include/fonts/symbols/**/*'


jobs:
  check-symbol-generation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install-deps
        run: |
          sudo apt update
          sudo apt install python3 python3-pip
      - name: Setup symbols script dependencies
        run: |
          cd ${{github.workspace}}
          pip3 install -r requirements.txt
      - name: Run symbols script
        run: ./scripts/generate_symbols.py
      - name: Fail the build if there are changes generated
        run: |
          git --no-pager diff
          git diff-index --quiet HEAD
